version: '3'
services:
  flask-app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: api-maps:latest
    ports:
      - "8100:8100"
    env_file:
      - ./backend/.env
  vue-app:
    build: 
      context: ./front-map
      dockerfile: Dockerfile
    image: web-maps:latest
    ports:
      - "8080:8080"
    depends_on:
      - flask-app
